number1 = int(input("첫 번째 정수 입력:"))
number2 = int(input("두 번째 정수 입력:"))
print("-"*20)
print(number1,"+",number2,"=",(number1+number2))
print(number1,"-",number2,"=",(number1-number2))
print(number1,"*",number2,"=",(number1*number2))
print(number1,"/",number2,"=",(number1/number2))
print("-"*20)
print("%d + %d = %d"%(number1, number2, number1+number2))
print("%d - %d = %d"%(number1, number2, number1-number2))
print("%d * %d = %d"%(number1, number2, number1*number2))
print("%d / %d = %0.2f"%(number1, number2, number1/number2))
print("-"*20)
print(f"{number1} + {number2} = {number1+number2}")
print(f"{number1} - {number2} = {number1-number2}")
print(f"{number1} * {number2} = {number1*number2}")
print(f"{number1} / {number2} = {number1/number2:.2f}")
print("-"*20)
print("{0} + {1} = {2}".format(number1, number2, number1+number2))
print("{0} - {1} = {2}".format(number1, number2, number1-number2))
print("{0} * {1} = {2}".format(number1, number2, number1*number2))
print("{0} / {1} = {2:.2f}".format(number1, number2, number1/number2))
print("-"*20)
